# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myDemoApp

  target 'myDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myDemoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myDemoApp-tvOS

  target 'myDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
