# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myDemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myDemoApp

  target 'myDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-video', :path => '../node_modules/react-native-video'

    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'RNAudioStreaming', :path => '../node_modules/react-native-audio-streaming'

  end

  target 'myDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myDemoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myDemoApp-tvOS
 pod 'react-native-video', path: '../node_modules/react-native-video'
  target 'myDemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
